/** Languages the archive can display. `en` is the site default and needs no URL prefix. */
export interface Language {
  code: string;
  name: string;
  nativeName: string;
  /** BCP-47 prefix used to pick a speech-synthesis voice. */
  speech: string;
  ui: {
    readIn: string;
    original: string;
    machineNotice: string;
    translating: string;
    read: string;
    listen: string;
    play: string;
    pause: string;
    resume: string;
    stop: string;
    speed: string;
    voice: string;
    sharedBy: string;
    testimonyOf: string;
    via: string;
    unnamedWitness: string;
    audioHint: string;
    partOf: (n: number, total: number) => string;
  };
}

export const DEFAULT_LANGUAGE = "en";

export const LANGUAGES: Language[] = [
  {
    code: "en",
    name: "English",
    nativeName: "English",
    speech: "en",
    ui: {
      readIn: "Read in English",
      original: "Original",
      machineNotice: "Machine translation. The author's original words are in {lang}.",
      translating: "Translating…",
      read: "Read",
      listen: "Listen",
      play: "Play",
      pause: "Pause",
      resume: "Resume",
      stop: "Stop",
      speed: "Speed",
      voice: "Voice",
      sharedBy: "Shared by",
      testimonyOf: "The testimony of",
      via: "via",
      unnamedWitness: "an unnamed witness",
      audioHint: "Audio is generated by your device's built-in voice. Click any paragraph to start from there. On a Mac or iPhone, an \"Enhanced\" or \"Premium\" voice downloaded in Accessibility → Spoken Content sounds far more natural and will appear in the voice list here.",
      partOf: (n, total) => `Part ${n} of ${total}`,
    },
  },
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    speech: "es",
    ui: {
      readIn: "Leer en español",
      original: "Original",
      machineNotice: "Traducción automática. Las palabras originales del autor están en {lang}.",
      translating: "Traduciendo…",
      read: "Leer",
      listen: "Escuchar",
      play: "Reproducir",
      pause: "Pausar",
      resume: "Continuar",
      stop: "Detener",
      speed: "Velocidad",
      voice: "Voz",
      sharedBy: "Compartido por",
      testimonyOf: "El testimonio de",
      via: "vía",
      unnamedWitness: "un testigo sin nombre",
      audioHint: "El audio lo genera la voz integrada de tu dispositivo. Toca cualquier párrafo para empezar desde ahí. En Mac o iPhone, una voz \"Mejorada\" o \"Premium\" descargada en Accesibilidad → Contenido hablado suena mucho más natural y aparecerá en la lista de voces.",
      partOf: (n, total) => `Parte ${n} de ${total}`,
    },
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    speech: "pt",
    ui: {
      readIn: "Ler em português",
      original: "Original",
      machineNotice: "Tradução automática. As palavras originais do autor estão em {lang}.",
      translating: "Traduzindo…",
      read: "Ler",
      listen: "Ouvir",
      play: "Reproduzir",
      pause: "Pausar",
      resume: "Continuar",
      stop: "Parar",
      speed: "Velocidade",
      voice: "Voz",
      sharedBy: "Compartilhado por",
      testimonyOf: "O testemunho de",
      via: "via",
      unnamedWitness: "uma testemunha sem nome",
      audioHint: "O áudio é gerado pela voz integrada do seu dispositivo. Toque em qualquer parágrafo para começar a partir dali. No Mac ou iPhone, uma voz \"Aprimorada\" ou \"Premium\" baixada em Acessibilidade → Conteúdo falado soa muito mais natural e aparecerá na lista de vozes.",
      partOf: (n, total) => `Parte ${n} de ${total}`,
    },
  },
];

export function languageByCode(code: string | null | undefined): Language | undefined {
  if (!code) return undefined;
  return LANGUAGES.find((l) => l.code === code.toLowerCase());
}

export function isSupportedLanguage(code: string): boolean {
  return !!languageByCode(code);
}

/** Name of a language as written in another language (good enough for the notice line). */
export function languageNameIn(target: string, viewer: string): string {
  const lang = languageByCode(target);
  if (!lang) return target;
  try {
    const dn = new Intl.DisplayNames([viewer], { type: "language" });
    return dn.of(target) ?? lang.nativeName;
  } catch {
    return lang.nativeName;
  }
}
